/** Mock print: renders the markdown-ish handout into a printable window. */

function escapeHtml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function inline(value: string) {
  return escapeHtml(value)
    .replace(/(\*\*|__)(.+?)\1/g, "<strong>$2</strong>")
    .replace(/(?<!\*)\*(?!\s)(.+?)(?<!\s)\*(?!\*)/g, "<em>$1</em>")
    .replace(/`([^`]+)`/g, "<code>$1</code>");
}

export function markdownToPrintHtml(text: string) {
  const lines = text.replace(/\r\n/g, "\n").split("\n");
  const out: string[] = [];
  let list: "ul" | "ol" | null = null;

  const closeList = () => {
    if (list) {
      out.push(`</${list}>`);
      list = null;
    }
  };

  for (const raw of lines) {
    const line = raw.trim();
    if (!line) {
      closeList();
      continue;
    }
    if (/^(?:---+|\*\*\*+|___+)$/.test(line)) {
      closeList();
      out.push("<hr />");
      continue;
    }
    const heading = line.match(/^(#{1,6})\s+(.*)$/);
    if (heading) {
      closeList();
      const level = Math.min((heading[1] ?? "#").length + 1, 6);
      out.push(`<h${level}>${inline(heading[2] ?? "")}</h${level}>`);
      continue;
    }
    const ordered = line.match(/^\d+[.)]\s+(.*)$/);
    const bulleted = line.match(/^[-*•]\s+(.*)$/);
    if (ordered || bulleted) {
      const kind: "ul" | "ol" = ordered ? "ol" : "ul";
      if (list !== kind) {
        closeList();
        out.push(`<${kind}>`);
        list = kind;
      }
      out.push(`<li>${inline((ordered ? ordered[1] : bulleted?.[1]) ?? "")}</li>`);
      continue;
    }
    closeList();
    out.push(`<p>${inline(line)}</p>`);
  }
  closeList();
  return out.join("\n");
}

export function printHandout(options: {
  title: string;
  subtitle?: string;
  text: string;
}) {
  const win = window.open("", "_blank", "width=820,height=1000");
  if (!win) return false;

  win.document.write(`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>${escapeHtml(options.title)}</title>
<style>
  * { box-sizing: border-box; }
  body { font-family: ui-sans-serif, system-ui, -apple-system, "Segoe UI", sans-serif; color: #14231f; margin: 0; padding: 40px; line-height: 1.55; }
  .sheet { max-width: 680px; margin: 0 auto; }
  header { border-bottom: 2px solid #0f766e; padding-bottom: 12px; margin-bottom: 24px; }
  .brand { font-size: 12px; letter-spacing: .18em; text-transform: uppercase; color: #0f766e; font-weight: 600; }
  h1 { font-size: 22px; margin: 6px 0 2px; }
  .subtitle { font-size: 13px; color: #5b6b66; margin: 0; }
  h2 { font-size: 16px; margin: 22px 0 6px; }
  h3, h4, h5, h6 { font-size: 14px; margin: 18px 0 4px; }
  p { margin: 0 0 10px; font-size: 13.5px; }
  ul, ol { margin: 0 0 12px; padding-left: 22px; font-size: 13.5px; }
  li { margin-bottom: 4px; }
  hr { border: 0; border-top: 1px solid #d8e3e0; margin: 18px 0; }
  code { background: #eef4f2; padding: 1px 4px; border-radius: 4px; font-size: 12.5px; }
  footer { margin-top: 32px; border-top: 1px solid #d8e3e0; padding-top: 10px; font-size: 11px; color: #7b8a86; }
  @media print { body { padding: 0; } }
</style>
</head>
<body>
  <div class="sheet">
    <header>
      <div class="brand">Ante · After-visit summary</div>
      <h1>${escapeHtml(options.title)}</h1>
      ${options.subtitle ? `<p class="subtitle">${escapeHtml(options.subtitle)}</p>` : ""}
    </header>
    ${markdownToPrintHtml(options.text)}
    <footer>Generated by Ante — demo document, not a legal medical record.</footer>
  </div>
  <script>window.onload = function () { window.print(); };<\/script>
</body>
</html>`);
  win.document.close();
  return true;
}
