/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedClinicalRouteImport } from './routes/_authenticated/clinical'
import { Route as AuthenticatedPassportRouteImport } from './routes/_authenticated/passport'
import { Route as AuthenticatedPatientsRouteImport } from './routes/_authenticated/patients'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSurveillanceRouteImport } from './routes/_authenticated/surveillance'
import { Route as AuthenticatedVisitsRouteImport } from './routes/_authenticated/visits'
import { Route as ApiIntakeRouteImport } from './routes/api/intake'
import { Route as ApiProcessVisitRouteImport } from './routes/api/process-visit'
import { Route as ApiStreamSessionRouteImport } from './routes/api/stream-session'
import { Route as ApiSttSessionRouteImport } from './routes/api/stt-session'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiVerifyDoctorRouteImport } from './routes/api/verify-doctor'
import { Route as AuthenticatedConsultationVisitIdRouteImport } from './routes/_authenticated/consultation.$visitId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClinicalRoute = AuthenticatedClinicalRouteImport.update({
  id: '/clinical',
  path: '/clinical',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPassportRoute = AuthenticatedPassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPatientsRoute = AuthenticatedPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSurveillanceRoute =
  AuthenticatedSurveillanceRouteImport.update({
    id: '/surveillance',
    path: '/surveillance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVisitsRoute = AuthenticatedVisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiIntakeRoute = ApiIntakeRouteImport.update({
  id: '/api/intake',
  path: '/api/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProcessVisitRoute = ApiProcessVisitRouteImport.update({
  id: '/api/process-visit',
  path: '/api/process-visit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamSessionRoute = ApiStreamSessionRouteImport.update({
  id: '/api/stream-session',
  path: '/api/stream-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSttSessionRoute = ApiSttSessionRouteImport.update({
  id: '/api/stt-session',
  path: '/api/stt-session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyDoctorRoute = ApiVerifyDoctorRouteImport.update({
  id: '/api/verify-doctor',
  path: '/api/verify-doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConsultationVisitIdRoute =
  AuthenticatedConsultationVisitIdRouteImport.update({
    id: '/consultation/$visitId',
    path: '/consultation/$visitId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clinical': typeof AuthenticatedClinicalRoute
  '/passport': typeof AuthenticatedPassportRoute
  '/patients': typeof AuthenticatedPatientsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/surveillance': typeof AuthenticatedSurveillanceRoute
  '/visits': typeof AuthenticatedVisitsRoute
  '/api/intake': typeof ApiIntakeRoute
  '/api/process-visit': typeof ApiProcessVisitRoute
  '/api/stream-session': typeof ApiStreamSessionRoute
  '/api/stt-session': typeof ApiSttSessionRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/verify-doctor': typeof ApiVerifyDoctorRoute
  '/consultation/$visitId': typeof AuthenticatedConsultationVisitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clinical': typeof AuthenticatedClinicalRoute
  '/passport': typeof AuthenticatedPassportRoute
  '/patients': typeof AuthenticatedPatientsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/surveillance': typeof AuthenticatedSurveillanceRoute
  '/visits': typeof AuthenticatedVisitsRoute
  '/api/intake': typeof ApiIntakeRoute
  '/api/process-visit': typeof ApiProcessVisitRoute
  '/api/stream-session': typeof ApiStreamSessionRoute
  '/api/stt-session': typeof ApiSttSessionRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/verify-doctor': typeof ApiVerifyDoctorRoute
  '/consultation/$visitId': typeof AuthenticatedConsultationVisitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/clinical': typeof AuthenticatedClinicalRoute
  '/_authenticated/passport': typeof AuthenticatedPassportRoute
  '/_authenticated/patients': typeof AuthenticatedPatientsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/surveillance': typeof AuthenticatedSurveillanceRoute
  '/_authenticated/visits': typeof AuthenticatedVisitsRoute
  '/api/intake': typeof ApiIntakeRoute
  '/api/process-visit': typeof ApiProcessVisitRoute
  '/api/stream-session': typeof ApiStreamSessionRoute
  '/api/stt-session': typeof ApiSttSessionRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/verify-doctor': typeof ApiVerifyDoctorRoute
  '/_authenticated/consultation/$visitId': typeof AuthenticatedConsultationVisitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/clinical'
    | '/passport'
    | '/patients'
    | '/settings'
    | '/surveillance'
    | '/visits'
    | '/api/intake'
    | '/api/process-visit'
    | '/api/stream-session'
    | '/api/stt-session'
    | '/api/transcribe'
    | '/api/verify-doctor'
    | '/consultation/$visitId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/clinical'
    | '/passport'
    | '/patients'
    | '/settings'
    | '/surveillance'
    | '/visits'
    | '/api/intake'
    | '/api/process-visit'
    | '/api/stream-session'
    | '/api/stt-session'
    | '/api/transcribe'
    | '/api/verify-doctor'
    | '/consultation/$visitId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/clinical'
    | '/_authenticated/passport'
    | '/_authenticated/patients'
    | '/_authenticated/settings'
    | '/_authenticated/surveillance'
    | '/_authenticated/visits'
    | '/api/intake'
    | '/api/process-visit'
    | '/api/stream-session'
    | '/api/stt-session'
    | '/api/transcribe'
    | '/api/verify-doctor'
    | '/_authenticated/consultation/$visitId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiIntakeRoute: typeof ApiIntakeRoute
  ApiProcessVisitRoute: typeof ApiProcessVisitRoute
  ApiStreamSessionRoute: typeof ApiStreamSessionRoute
  ApiSttSessionRoute: typeof ApiSttSessionRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiVerifyDoctorRoute: typeof ApiVerifyDoctorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clinical': {
      id: '/_authenticated/clinical'
      path: '/clinical'
      fullPath: '/clinical'
      preLoaderRoute: typeof AuthenticatedClinicalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/passport': {
      id: '/_authenticated/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof AuthenticatedPassportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients': {
      id: '/_authenticated/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AuthenticatedPatientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/surveillance': {
      id: '/_authenticated/surveillance'
      path: '/surveillance'
      fullPath: '/surveillance'
      preLoaderRoute: typeof AuthenticatedSurveillanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/visits': {
      id: '/_authenticated/visits'
      path: '/visits'
      fullPath: '/visits'
      preLoaderRoute: typeof AuthenticatedVisitsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/intake': {
      id: '/api/intake'
      path: '/api/intake'
      fullPath: '/api/intake'
      preLoaderRoute: typeof ApiIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/process-visit': {
      id: '/api/process-visit'
      path: '/api/process-visit'
      fullPath: '/api/process-visit'
      preLoaderRoute: typeof ApiProcessVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream-session': {
      id: '/api/stream-session'
      path: '/api/stream-session'
      fullPath: '/api/stream-session'
      preLoaderRoute: typeof ApiStreamSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stt-session': {
      id: '/api/stt-session'
      path: '/api/stt-session'
      fullPath: '/api/stt-session'
      preLoaderRoute: typeof ApiSttSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify-doctor': {
      id: '/api/verify-doctor'
      path: '/api/verify-doctor'
      fullPath: '/api/verify-doctor'
      preLoaderRoute: typeof ApiVerifyDoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/consultation/$visitId': {
      id: '/_authenticated/consultation/$visitId'
      path: '/consultation/$visitId'
      fullPath: '/consultation/$visitId'
      preLoaderRoute: typeof AuthenticatedConsultationVisitIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClinicalRoute: typeof AuthenticatedClinicalRoute
  AuthenticatedPassportRoute: typeof AuthenticatedPassportRoute
  AuthenticatedPatientsRoute: typeof AuthenticatedPatientsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSurveillanceRoute: typeof AuthenticatedSurveillanceRoute
  AuthenticatedVisitsRoute: typeof AuthenticatedVisitsRoute
  AuthenticatedConsultationVisitIdRoute: typeof AuthenticatedConsultationVisitIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClinicalRoute: AuthenticatedClinicalRoute,
  AuthenticatedPassportRoute: AuthenticatedPassportRoute,
  AuthenticatedPatientsRoute: AuthenticatedPatientsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSurveillanceRoute: AuthenticatedSurveillanceRoute,
  AuthenticatedVisitsRoute: AuthenticatedVisitsRoute,
  AuthenticatedConsultationVisitIdRoute: AuthenticatedConsultationVisitIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiIntakeRoute: ApiIntakeRoute,
  ApiProcessVisitRoute: ApiProcessVisitRoute,
  ApiStreamSessionRoute: ApiStreamSessionRoute,
  ApiSttSessionRoute: ApiSttSessionRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiVerifyDoctorRoute: ApiVerifyDoctorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
